<%@ Page Language="C#" AutoEventWireup="true" CodeFile="ApplyEdit.aspx.cs" Inherits="NextWebF" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>edit</title>
</head>
<body>
    <form id="form1" runat="server">
    
        <asp:SqlDataSource ID="SqlDataSourceRoomApply" runat="server" ConnectionString="<%$ ConnectionStrings:webTestConnectionString %>" SelectCommand="  select distinct a.strRoom,a.intDay,a.intStartNum,a.intStartWeek,a.intEndWeek,a.intEndNum,a.strName,a.strClass,a.strTeacher from RoomApply a ,RoomDetail d where a.strRoom = d.strRoomName and d.strDepart = @strDepart">
            <SelectParameters>
                <asp:ControlParameter ControlID ="DropDownListDepart" Name ="strDepart" PropertyName ="SelectedValue" Type ="String" />
            </SelectParameters>
        </asp:SqlDataSource>       
        <asp:SqlDataSource ID="SqlDataSourceDepartment" runat="server" ConnectionString="<%$ ConnectionStrings:webTestConnectionString %>" SelectCommand="SELECT distinct RTRIM(strDepart) strDepart FROM [RoomDetail]"></asp:SqlDataSource>
        <asp:DropDownList ID="DropDownListDepart" runat="server" AutoPostBack="False" DataSourceID="SqlDataSourceDepartment" DataTextField="strDepart" DataValueField="strDepart"></asp:DropDownList>
           

        <asp:GridView ID="GridView10" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSourceRoomApply" EnableModelValidation="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AllowPaging="True" AllowSorting="True" HorizontalAlign="Left">
            <Columns>
                <asp:BoundField DataField="strRoom" HeaderText="strRoom" SortExpression="strRoom" />
                <asp:BoundField DataField="intDay" HeaderText="intDay" SortExpression="intDay" />
                <asp:BoundField DataField="intStartNum" HeaderText="intStartNum" SortExpression="intStartNum" />
                <asp:BoundField DataField="intStartWeek" HeaderText="intStartWeek" SortExpression="intStartWeek" />
                <asp:BoundField DataField="intEndWeek" HeaderText="intEndWeek" SortExpression="intEndWeek" />
                <asp:BoundField DataField="intEndNum" HeaderText="intEndNum" SortExpression="intEndNum" />
                <asp:BoundField DataField="strName" HeaderText="strName" SortExpression="strName" />
                <asp:BoundField DataField="strClass" HeaderText="strClass" SortExpression="strClass" />
                <asp:BoundField DataField="strTeacher" HeaderText="strTeacher" SortExpression="strTeacher" />
            </Columns>
        </asp:GridView>

        

    </form>
</body>
</html>
